name: Android Testing CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Unit test
        run: ./gradlew test

      - name: Android  Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}

